log exceptions in the JRStyledTextParser static initializer
such exceptions are obscured behind NoClassDefFoundErrors, making it
difficult to tell what the root cause is.